before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli/
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
    goarm:
      - 6
      - 7
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
nfpms:
  - vendor: Elastic Infra
    homepage: https://elastic-infra.com/
    maintainer: Tomoya Kabe <kabe@elastic-infra.com>
    license: MIT
    description: Gradual rm
    formats:
      - deb
      - rpm
    bindir: /usr/bin
release:
  github:
    owner: elastic-infra
    name: go-remove-slowly
