version: 2.1

orbs:
  go: circleci/go@1.4.0
  slack: circleci/slack@4.5.0

executors:
  builder:
    working_directory: /go/src/github.com/elastic-infra/go-remove-slowly
    docker:
      - image: circleci/golang:1.15
    environment:
      GO111MODULE: 'on'

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: Build
          command: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --clean
      - store_artifacts:
          path: dist/
          destination: dist
      - slack/notify:
          event: fail
          template: basic_fail_1
  release:
    executor: builder
    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: Go Releaser
          command: curl -sL https://git.io/goreleaser | bash
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  
  test:
    executor: builder
    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: Run Test
          command: |
            make test
      - store_test_results:
          path: /tmp/test_results
      - store_artifacts:
          path: test/
          destination: test
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  test_build_or_release:
    jobs:
      - test:
          context:
            - SlackApp-OAuth
          filters:
            tags:
              only: /.*/
      - build:
          context:
            - SlackApp-OAuth
          requires:
            - test
          filters:
            tags:
              ignore: /^v.*/
      - release:
          context:
            - SlackApp-OAuth
            - GithubRelease
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  nightly:
    jobs:
      - test:
          context:
            - SlackApp-OAuth
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
